---
title: "STT 465 HW4"
author: "Nate Davis"
date: "11/20/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

```{r}

library("coda")

data <- read.table("gout.txt")

colnames(data)=c('sex','race','age','serum_urate','gout')

data$sex=factor(data$sex,levels=c('M','F'))
data$race=as.factor(data$race) 

sex <- ifelse(data$sex=='F',1,0) # a dummy variable for female
race <- ifelse(data$race=='W',1,0) # a dummy variable for male

x <- cbind(1, sex, race, data$age) 
y <- data$serum_urate

```



### Gibbs Sampler Function

```{r}

gibbs_regression <- function(x, y, iter, burn_in, b_prior, df_prior, var_b){
    
    n <- nrow(x)
    p <- ncol(x)
    
    betas <- matrix(nrow = iter, ncol = p, 0)
    var_e <- rep(NA, iter)
    
    s_prior <- var(y) * 0.8 * (df_prior - 2)
    
    betas[1,] <- 0
    betas[1,1] <- mean(y)
    b <- betas[1,]
    var_e[1] <- var(y)
    resid <- y - betas[1,1]
    
    for(i in 2:ncol(x)){ x[,i] <- x[,i] - mean(x[,i]) }
    
    ssx <- colSums(x^2)
    
    for(i in 2:iter){
        
        for(j in 1:p){
            
            c <- ssx[j] / var_e[i-1] + 1 / var_b
            y_star <- y - x[,-j] %*% b[-j]
            rhs <- sum(x[,j] * y_star) / var_e[i-1] + b_prior / var_b
            
            cond_mean <- rhs / c
            cond_var <- 1 / c
            
            b[j] <- rnorm(n = 1, mean = cond_mean, sd = sqrt(cond_var))
            betas[i,j] <- b[j] 
        }
        
        rss <- sum(resid^2)
        df <- n + df_prior
        s <- rss + s_prior
        
        var_e[i] <- s / rchisq(df = df, n = 1)
    }
    
    out <- list(effects = betas, var_e = var_e)
    return(out)
}

```



### Run model


```{r}

reg <- gibbs_regression(x, y, iter = 20000, b_prior = 0, df_prior = 4, var_b = 10000)

reg_params <- data.frame(reg$effects)

colnames(reg_params) <- c("Intercept", "Sex", "Race", "Age")

```


## 1.1

```{r}

par(mfrow = c(2, 2))

plot(reg_params$Intercept, xlab = "Index", ylab = "Est", main = "Intercept")
plot(reg_params$Sex, xlab = "Index", ylab = "Est", main = "Sex")
plot(reg_params$Race, xlab = "Index", ylab = "Est", main = "Race")
plot(reg_params$Age, xlab = "Index", ylab = "Est", main = "Age")

```

From here we see that there is little need for burn in (the only parameter with a largely deviant initial value is sex). With our large sample size, it is most likely negligible but we can use a burn-in of 100 to correct:

```{r}

burn_in <- 100

reg_params <- reg_params[-(1:burn_in),]

```

## 1.2

```{r}

reg_mcmc <- mcmc(reg_params)

diag_ <- summary(reg_mcmc)

diag_

```


## 1.3

```{r}

autocorr.plot(reg_mcmc, lag.max = 100)

```


## 1.4

```{r}

effectiveSize(reg_mcmc)

```


## 1.5

```{r}

hpd <- HPDinterval(reg_mcmc)

par(mfrow = c(2, 2))

plot(density(reg_params$Intercept), xlab = "Est", ylab = "Density", main = "Intercept")
abline(v = diag_$statistics[1, 1], lty = 2)
abline(v = hpd[1, 1])
abline(v = hpd[1, 2])

plot(density(reg_params$Sex), xlab = "Est", ylab = "Density", main = "Sex")
abline(v = diag_$statistics[2, 1], lty = 2)
abline(v = hpd[2, 1])
abline(v = hpd[2, 2])

plot(density(reg_params$Race), xlab = "Est", ylab = "Density", main = "Race")
abline(v = diag_$statistics[3, 1], lty = 2)
abline(v = hpd[3, 1])
abline(v = hpd[3, 2])

plot(density(reg_params$Age), xlab = "Est", ylab = "Density", main = "Age")
abline(v = diag_$statistics[4, 1], lty = 2)
abline(v = hpd[4, 1])
abline(v = hpd[4, 2])

```

